name = "everylanguage-cdn"
main = "src/index.ts"
compatibility_date = "2024-06-20"

routes = [
  { pattern = "cdn.everylanguage.com/*", zone_id = "a26273709cc2529fca150f35c7b99827" }
]

[vars]
CDN_SIGNING_SECRET = ""

[[r2_buckets]]
binding = "R2_MEDIA_DEV"
bucket_name = "el-backend-dev-media-files"

[[r2_buckets]]
binding = "R2_MEDIA_PROD"
bucket_name = "el-backend-prod-media-files"


