-- Bible Version and Books
INSERT INTO
  bible_versions (id, name, structure_notes)
VALUES
  (
    'bible-version-protestant-standard',
    'Protestant Bible (Standard)',
    'Standard Protestant Bible with 66 books (39 Old Testament, 27 New Testament)'
  );


-- All Books
INSERT INTO
  books (id, name, book_number, bible_version_id)
VALUES
  (
    'book-genesis',
    'Genesis',
    1,
    'bible-version-protestant-standard'
  ),
  (
    'book-exodus',
    'Exodus',
    2,
    'bible-version-protestant-standard'
  ),
  (
    'book-leviticus',
    'Leviticus',
    3,
    'bible-version-protestant-standard'
  ),
  (
    'book-numbers',
    'Numbers',
    4,
    'bible-version-protestant-standard'
  ),
  (
    'book-deuteronomy',
    'Deuteronomy',
    5,
    'bible-version-protestant-standard'
  ),
  (
    'book-joshua',
    'Joshua',
    6,
    'bible-version-protestant-standard'
  ),
  (
    'book-judges',
    'Judges',
    7,
    'bible-version-protestant-standard'
  ),
  (
    'book-ruth',
    'Ruth',
    8,
    'bible-version-protestant-standard'
  ),
  (
    'book-1_samuel',
    '1 Samuel',
    9,
    'bible-version-protestant-standard'
  ),
  (
    'book-2_samuel',
    '2 Samuel',
    10,
    'bible-version-protestant-standard'
  ),
  (
    'book-1_kings',
    '1 Kings',
    11,
    'bible-version-protestant-standard'
  ),
  (
    'book-2_kings',
    '2 Kings',
    12,
    'bible-version-protestant-standard'
  ),
  (
    'book-1_chronicles',
    '1 Chronicles',
    13,
    'bible-version-protestant-standard'
  ),
  (
    'book-2_chronicles',
    '2 Chronicles',
    14,
    'bible-version-protestant-standard'
  ),
  (
    'book-ezra',
    'Ezra',
    15,
    'bible-version-protestant-standard'
  ),
  (
    'book-nehemiah',
    'Nehemiah',
    16,
    'bible-version-protestant-standard'
  ),
  (
    'book-esther',
    'Esther',
    17,
    'bible-version-protestant-standard'
  ),
  (
    'book-job',
    'Job',
    18,
    'bible-version-protestant-standard'
  ),
  (
    'book-psalms',
    'Psalms',
    19,
    'bible-version-protestant-standard'
  ),
  (
    'book-proverbs',
    'Proverbs',
    20,
    'bible-version-protestant-standard'
  ),
  (
    'book-ecclesiastes',
    'Ecclesiastes',
    21,
    'bible-version-protestant-standard'
  ),
  (
    'book-song_of_songs',
    'Song Of Songs',
    22,
    'bible-version-protestant-standard'
  ),
  (
    'book-isaiah',
    'Isaiah',
    23,
    'bible-version-protestant-standard'
  ),
  (
    'book-jeremiah',
    'Jeremiah',
    24,
    'bible-version-protestant-standard'
  ),
  (
    'book-lamentations',
    'Lamentations',
    25,
    'bible-version-protestant-standard'
  ),
  (
    'book-ezekiel',
    'Ezekiel',
    26,
    'bible-version-protestant-standard'
  ),
  (
    'book-daniel',
    'Daniel',
    27,
    'bible-version-protestant-standard'
  ),
  (
    'book-hosea',
    'Hosea',
    28,
    'bible-version-protestant-standard'
  ),
  (
    'book-joel',
    'Joel',
    29,
    'bible-version-protestant-standard'
  ),
  (
    'book-amos',
    'Amos',
    30,
    'bible-version-protestant-standard'
  ),
  (
    'book-obadiah',
    'Obadiah',
    31,
    'bible-version-protestant-standard'
  ),
  (
    'book-jonah',
    'Jonah',
    32,
    'bible-version-protestant-standard'
  ),
  (
    'book-micah',
    'Micah',
    33,
    'bible-version-protestant-standard'
  ),
  (
    'book-nahum',
    'Nahum',
    34,
    'bible-version-protestant-standard'
  ),
  (
    'book-habakkuk',
    'Habakkuk',
    35,
    'bible-version-protestant-standard'
  ),
  (
    'book-zephaniah',
    'Zephaniah',
    36,
    'bible-version-protestant-standard'
  ),
  (
    'book-haggai',
    'Haggai',
    37,
    'bible-version-protestant-standard'
  ),
  (
    'book-zechariah',
    'Zechariah',
    38,
    'bible-version-protestant-standard'
  ),
  (
    'book-malachi',
    'Malachi',
    39,
    'bible-version-protestant-standard'
  ),
  (
    'book-matthew',
    'Matthew',
    40,
    'bible-version-protestant-standard'
  ),
  (
    'book-mark',
    'Mark',
    41,
    'bible-version-protestant-standard'
  ),
  (
    'book-luke',
    'Luke',
    42,
    'bible-version-protestant-standard'
  ),
  (
    'book-john',
    'John',
    43,
    'bible-version-protestant-standard'
  ),
  (
    'book-acts',
    'Acts',
    44,
    'bible-version-protestant-standard'
  ),
  (
    'book-romans',
    'Romans',
    45,
    'bible-version-protestant-standard'
  ),
  (
    'book-1_corinthians',
    '1 Corinthians',
    46,
    'bible-version-protestant-standard'
  ),
  (
    'book-2_corinthians',
    '2 Corinthians',
    47,
    'bible-version-protestant-standard'
  ),
  (
    'book-galatians',
    'Galatians',
    48,
    'bible-version-protestant-standard'
  ),
  (
    'book-ephesians',
    'Ephesians',
    49,
    'bible-version-protestant-standard'
  ),
  (
    'book-philippians',
    'Philippians',
    50,
    'bible-version-protestant-standard'
  ),
  (
    'book-colossians',
    'Colossians',
    51,
    'bible-version-protestant-standard'
  ),
  (
    'book-1_thessalonians',
    '1 Thessalonians',
    52,
    'bible-version-protestant-standard'
  ),
  (
    'book-2_thessalonians',
    '2 Thessalonians',
    53,
    'bible-version-protestant-standard'
  ),
  (
    'book-1_timothy',
    '1 Timothy',
    54,
    'bible-version-protestant-standard'
  ),
  (
    'book-2_timothy',
    '2 Timothy',
    55,
    'bible-version-protestant-standard'
  ),
  (
    'book-titus',
    'Titus',
    56,
    'bible-version-protestant-standard'
  ),
  (
    'book-philemon',
    'Philemon',
    57,
    'bible-version-protestant-standard'
  ),
  (
    'book-hebrews',
    'Hebrews',
    58,
    'bible-version-protestant-standard'
  ),
  (
    'book-james',
    'James',
    59,
    'bible-version-protestant-standard'
  ),
  (
    'book-1_peter',
    '1 Peter',
    60,
    'bible-version-protestant-standard'
  ),
  (
    'book-2_peter',
    '2 Peter',
    61,
    'bible-version-protestant-standard'
  ),
  (
    'book-1_john',
    '1 John',
    62,
    'bible-version-protestant-standard'
  ),
  (
    'book-2_john',
    '2 John',
    63,
    'bible-version-protestant-standard'
  ),
  (
    'book-3_john',
    '3 John',
    64,
    'bible-version-protestant-standard'
  ),
  (
    'book-jude',
    'Jude',
    65,
    'bible-version-protestant-standard'
  ),
  (
    'book-revelation',
    'Revelation',
    66,
    'bible-version-protestant-standard'
  );
