-- Bible Version and Books
INSERT INTO
  bible_versions (id, name, structure_notes)
VALUES
  (
    'bible-version-protestant-standard',
    'Protestant Bible (Standard)',
    'Standard Protestant Bible with 66 books (39 Old Testament, 27 New Testament)'
  );


-- All Books
INSERT INTO
  books (id, name, book_number, bible_version_id)
VALUES
  (
    'gen',
    'Genesis',
    1,
    'bible-version-protestant-standard'
  ),
  (
    'exod',
    'Exodus',
    2,
    'bible-version-protestant-standard'
  ),
  (
    'lev',
    'Leviticus',
    3,
    'bible-version-protestant-standard'
  ),
  (
    'num',
    'Numbers',
    4,
    'bible-version-protestant-standard'
  ),
  (
    'deut',
    'Deuteronomy',
    5,
    'bible-version-protestant-standard'
  ),
  (
    'josh',
    'Joshua',
    6,
    'bible-version-protestant-standard'
  ),
  (
    'judg',
    'Judges',
    7,
    'bible-version-protestant-standard'
  ),
  (
    'ruth',
    'Ruth',
    8,
    'bible-version-protestant-standard'
  ),
  (
    '1sam',
    '1 Samuel',
    9,
    'bible-version-protestant-standard'
  ),
  (
    '2sam',
    '2 Samuel',
    10,
    'bible-version-protestant-standard'
  ),
  (
    '1kgs',
    '1 Kings',
    11,
    'bible-version-protestant-standard'
  ),
  (
    '2kgs',
    '2 Kings',
    12,
    'bible-version-protestant-standard'
  ),
  (
    '1chr',
    '1 Chronicles',
    13,
    'bible-version-protestant-standard'
  ),
  (
    '2chr',
    '2 Chronicles',
    14,
    'bible-version-protestant-standard'
  ),
  (
    'ezra',
    'Ezra',
    15,
    'bible-version-protestant-standard'
  ),
  (
    'neh',
    'Nehemiah',
    16,
    'bible-version-protestant-standard'
  ),
  (
    'esth',
    'Esther',
    17,
    'bible-version-protestant-standard'
  ),
  (
    'job',
    'Job',
    18,
    'bible-version-protestant-standard'
  ),
  (
    'ps',
    'Psalms',
    19,
    'bible-version-protestant-standard'
  ),
  (
    'prov',
    'Proverbs',
    20,
    'bible-version-protestant-standard'
  ),
  (
    'eccl',
    'Ecclesiastes',
    21,
    'bible-version-protestant-standard'
  ),
  (
    'song',
    'Song Of Songs',
    22,
    'bible-version-protestant-standard'
  ),
  (
    'isa',
    'Isaiah',
    23,
    'bible-version-protestant-standard'
  ),
  (
    'jer',
    'Jeremiah',
    24,
    'bible-version-protestant-standard'
  ),
  (
    'lam',
    'Lamentations',
    25,
    'bible-version-protestant-standard'
  ),
  (
    'ezek',
    'Ezekiel',
    26,
    'bible-version-protestant-standard'
  ),
  (
    'dan',
    'Daniel',
    27,
    'bible-version-protestant-standard'
  ),
  (
    'hos',
    'Hosea',
    28,
    'bible-version-protestant-standard'
  ),
  (
    'joel',
    'Joel',
    29,
    'bible-version-protestant-standard'
  ),
  (
    'amos',
    'Amos',
    30,
    'bible-version-protestant-standard'
  ),
  (
    'obad',
    'Obadiah',
    31,
    'bible-version-protestant-standard'
  ),
  (
    'jonah',
    'Jonah',
    32,
    'bible-version-protestant-standard'
  ),
  (
    'mic',
    'Micah',
    33,
    'bible-version-protestant-standard'
  ),
  (
    'nah',
    'Nahum',
    34,
    'bible-version-protestant-standard'
  ),
  (
    'hab',
    'Habakkuk',
    35,
    'bible-version-protestant-standard'
  ),
  (
    'zeph',
    'Zephaniah',
    36,
    'bible-version-protestant-standard'
  ),
  (
    'hag',
    'Haggai',
    37,
    'bible-version-protestant-standard'
  ),
  (
    'zech',
    'Zechariah',
    38,
    'bible-version-protestant-standard'
  ),
  (
    'mal',
    'Malachi',
    39,
    'bible-version-protestant-standard'
  ),
  (
    'matt',
    'Matthew',
    40,
    'bible-version-protestant-standard'
  ),
  (
    'mark',
    'Mark',
    41,
    'bible-version-protestant-standard'
  ),
  (
    'luke',
    'Luke',
    42,
    'bible-version-protestant-standard'
  ),
  (
    'john',
    'John',
    43,
    'bible-version-protestant-standard'
  ),
  (
    'acts',
    'Acts',
    44,
    'bible-version-protestant-standard'
  ),
  (
    'rom',
    'Romans',
    45,
    'bible-version-protestant-standard'
  ),
  (
    '1cor',
    '1 Corinthians',
    46,
    'bible-version-protestant-standard'
  ),
  (
    '2cor',
    '2 Corinthians',
    47,
    'bible-version-protestant-standard'
  ),
  (
    'gal',
    'Galatians',
    48,
    'bible-version-protestant-standard'
  ),
  (
    'eph',
    'Ephesians',
    49,
    'bible-version-protestant-standard'
  ),
  (
    'phil',
    'Philippians',
    50,
    'bible-version-protestant-standard'
  ),
  (
    'col',
    'Colossians',
    51,
    'bible-version-protestant-standard'
  ),
  (
    '1thess',
    '1 Thessalonians',
    52,
    'bible-version-protestant-standard'
  ),
  (
    '2thess',
    '2 Thessalonians',
    53,
    'bible-version-protestant-standard'
  ),
  (
    '1tim',
    '1 Timothy',
    54,
    'bible-version-protestant-standard'
  ),
  (
    '2tim',
    '2 Timothy',
    55,
    'bible-version-protestant-standard'
  ),
  (
    'titus',
    'Titus',
    56,
    'bible-version-protestant-standard'
  ),
  (
    'phlm',
    'Philemon',
    57,
    'bible-version-protestant-standard'
  ),
  (
    'heb',
    'Hebrews',
    58,
    'bible-version-protestant-standard'
  ),
  (
    'jas',
    'James',
    59,
    'bible-version-protestant-standard'
  ),
  (
    '1pet',
    '1 Peter',
    60,
    'bible-version-protestant-standard'
  ),
  (
    '2pet',
    '2 Peter',
    61,
    'bible-version-protestant-standard'
  ),
  (
    '1john',
    '1 John',
    62,
    'bible-version-protestant-standard'
  ),
  (
    '2john',
    '2 John',
    63,
    'bible-version-protestant-standard'
  ),
  (
    '3john',
    '3 John',
    64,
    'bible-version-protestant-standard'
  ),
  (
    'jude',
    'Jude',
    65,
    'bible-version-protestant-standard'
  ),
  (
    'rev',
    'Revelation',
    66,
    'bible-version-protestant-standard'
  );
