name: Deploy to Development

on:
  push:
    branches: [develop]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Development project
        run: supabase link --project-ref ${{ secrets.SUPABASE_DEV_PROJECT_REF }} --password ${{ secrets.SUPABASE_DEV_DB_PASSWORD }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy configuration to Development
        run: |
          echo "📝 Deploying configuration changes to development environment..."
          ./scripts/deploy-config.sh ${{ secrets.SUPABASE_DEV_PROJECT_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_VERIFY_SERVICE_SID: ${{ secrets.TWILIO_VERIFY_SERVICE_SID }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

      - name: Deploy database migrations to Development
        run: supabase db push --password ${{ secrets.SUPABASE_DEV_DB_PASSWORD }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy Edge Functions to Development (if any exist)
        run: |
          if [ -d "supabase/functions" ] && [ "$(ls -A supabase/functions)" ]; then
            echo "Deploying Edge Functions to Development..."
            supabase functions deploy --no-verify-jwt
          else
            echo "No Edge Functions to deploy"
          fi
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Configure B2 CORS for Development
        run: backblaze/deployment/deploy-cors-ci.sh dev
        env:
          B2_KEY_ID: ${{ secrets.B2_KEY_ID }}
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
          B2_DEV_BUCKET_NAME: ${{ secrets.B2_DEV_BUCKET_NAME }}

      - name: Verify development deployment success
        run: |
          echo "✅ Database migrations deployed to development project successfully"
          echo "⚙️  Configuration changes from config.toml applied automatically"
          echo "📧 Email templates and SMTP settings updated"
          echo "🔄 Dev types must be published manually"
          echo "🚀 Development environment updated"
