name: Deploy to Development

on:
  push:
    branches: [develop]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Development project
        run: supabase link --project-ref ${{ secrets.SUPABASE_DEV_PROJECT_REF }} --password ${{ secrets.SUPABASE_DEV_DB_PASSWORD }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy configuration to Development
        run: |
          echo "📝 Deploying configuration changes to development environment..."
          ./scripts/deploy-config.sh ${{ secrets.SUPABASE_DEV_PROJECT_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_VERIFY_SERVICE_SID: ${{ secrets.TWILIO_VERIFY_SERVICE_SID }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

      - name: Deploy database migrations to Development
        run: supabase db push --password ${{ secrets.SUPABASE_DEV_DB_PASSWORD }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy Edge Functions to Development (only existing)
        run: |
          set -e
          if [ -d "supabase/functions" ]; then
            echo "Discovering edge function directories..."
            FUNCTIONS=$(find supabase/functions -maxdepth 1 -mindepth 1 -type d -exec test -f "{}/index.ts" ';' -print | xargs -I{} basename {} | tr '\n' ' ')
            if [ -n "$FUNCTIONS" ]; then
              echo "Deploying: $FUNCTIONS"
              supabase functions deploy $FUNCTIONS --no-verify-jwt
            else
              echo "No Edge Functions with index.ts to deploy"
            fi
          else
            echo "supabase/functions directory not found"
          fi
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Setup AWS CLI for R2 CORS Management
        run: |
          # Install AWS CLI if not present
          if ! command -v aws &> /dev/null; then
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          fi
          
      - name: Deploy R2 CORS Policies
        run: |
          echo "🔧 Configuring CORS for development buckets..."
          echo "⚠️  This ONLY updates CORS policies, never creates/deletes buckets"
          
          # Apply CORS for development environment
          cd cloudflare/cors
          chmod +x apply-cors.sh
          ./apply-cors.sh dev
        env:
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Setup Node.js 20 for Worker  
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Deploy Cloudflare Worker to Development
        if: ${{ env.STORAGE_PROVIDER == 'r2' || true }}
        run: |
          cd cloudflare/worker
          npm ci || true
          echo "${{ secrets.CDN_SIGNING_SECRET }}" | npx wrangler secret put CDN_SIGNING_SECRET
          npx wrangler deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_WORKERS }}

      - name: Verify development deployment success
        run: |
          echo "✅ Database migrations deployed to development project successfully"
          echo "⚙️  Configuration changes from config.toml applied automatically"
          echo "📧 Email templates and SMTP settings updated"
          echo "☁️  R2 CORS policies updated (buckets managed separately)"
          echo "🚀 Cloudflare Worker deployed with R2 bucket access"
          echo "🔄 Dev types must be published manually"
          echo "🚀 Development environment updated"
