name = "everylanguage-sqlite-package-api"
main = "src/index.ts"
compatibility_date = "2024-06-20"
compatibility_flags = []

[build]
upload.format = "service-worker"

[wasm_modules]
SQLITE_WASM = "node_modules/@powersync/wa-sqlite/dist/wa-sqlite.wasm"

[[r2_buckets]]
binding = "R2_MEDIA_DEV"
bucket_name = "el-backend-dev-media-files"

[[r2_buckets]]
binding = "R2_MEDIA_PROD"
bucket_name = "el-backend-prod-media-files"

[[hyperdrive]]
binding = "PG_DEV"
id = "ad912ae5ca044465be71898b5e55e6df"

[[hyperdrive]]
binding = "PG_PROD"
id = "bb63603d176c4fa0b21410f69e3357ad"

[observability]
enabled = true
head_sampling_rate = 1.0




